CREATE TABLE cars.TRANSACTION(
    TRANSACTION_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NAME TEXT NOT NULL ,
    CUSTOMER_NAME TEXT NOT NULL ,
    DATE TEXT NOT NULL ,
    CAR_ID BIGINT(20),
    CONSTRAINT FK_CAR_ID FOREIGN KEY(CAR_ID) REFERENCES CARS(CAR_ID)
);